base_url = """
http://localhost:3000
"""
last_selected_route = "fastify:GET:/teams:/home/daksh/Volt/tests/fixtures/fastify.ts"

[drafts."express:POST:/users:/home/daksh/Volt/tests/fixtures/express.ts"]
headers = """
:
:
: q"""
body = ""
params = """
:
:
: """
auth = """
:
:
: """

[drafts."custom:GET:/about:<custom>"]
headers = """
:
: """
body = ""
params = ": "
auth = ": "

[drafts."custom:GET:/stack:<custom>"]
headers = """
api key:
: q"""
body = ""
params = ": "
auth = ": "

[drafts.default]
headers = ": "
body = ""
params = ": "
auth = ": "

[drafts."custom:GET:https://dummyjson.com/todos:<custom>"]
headers = ": "
body = ""
params = ": "
auth = ": "

[drafts."fastapi:GET:/items:/home/daksh/Volt/tests/fixtures/fastapi.py"]
headers = """
:
: """
body = ""
params = """
:
: """
auth = """
:
: """

[drafts."custom:GET:/todos/1:<custom>"]
headers = ": "
body = ""
params = ": "
auth = ": "

[drafts."custom:GET:/todos:<custom>"]
headers = ": "
body = ""
params = ": "
auth = ": "
